### PR TITLE
port uuid

### PR DESCRIPTION
**Pull request by thuibr**

### CODE REVIEW

**Comment by thuibr** [comment]
I want to try again from a clean version and add type hints from https://github.com/python/typeshed/blob/main/stdlib/uuid.pyi first, seeing what's left to add after that. Also, this gets all the way to `./build.py test_compiled uuid` without failing but then I get `FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pycompiled/__pycache__'`. This is running on a Macbook Pro M1 and Python 3.11.5.

**Comment by thuibr** [comment]
@tusharsadhwani does this work on your machine?

**Comment by tusharsadhwani** [comment]
Hey! Thanks for the port. Why didn't I think of using typeshed (and Microsoft's stubs) before!

That error is probably because of a bug in the build script. I'll take a look later today.

**Comment by tusharsadhwani** [comment]
@thuibr `test_compiled` had a tiny bug which got triggered in this case, but unfortunately after that went through, the tests failed in the `test_compiled` setup.

```console
$ ./build.py test_compiled uuid
EEEEEssE.F.ssEEEEEssE.....EEEEEEsEsssEs...E..EEEEEEsEsssEs...E

[...]

FAILED (failures=1, errors=30, skipped=16)
```

**Comment by thuibr** [comment]
Thank you for fixing that. I'm taking a look at the errors. I'm looking at the last one that shows up for me:
```
======================================================================
FAIL: test_parse_mac_aix (compiled_tests.test_uuid.TestInternalsWithExtModule.test_parse_mac_aix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/pycompiled/compiled_tests/test_uuid.py", line 739, in test_parse_mac_aix
    self.check_parse_mac(True)
  File "/private/tmp/pycompiled/compiled_tests/test_uuid.py", line 712, in check_parse_mac
    self.assertEqual(self.uuid._parse_mac(mac), expected)
AssertionError: None != 280019184198404

----------------------------------------------------------------------
Ran 62 tests in 0.092s

FAILED (failures=1, errors=28, skipped=18)
```
I reckon that `mock.patch` does not work with the `mypyc` version, and that `_MAC_DELIM` is not actually set to `b'.'`, causing the error.

**Comment by thuibr** [comment]
See https://mypyc.readthedocs.io/en/latest/differences_from_python.html#monkey-patching

**Comment by tusharsadhwani** [comment]
Sorry for the silence, I'll look into this later this month!

**Comment by thuibr** [comment]
No worries! Maybe the folks at the mypyc project would have a solution.

**Pull request closed without merging**
